name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
autolabeler:
  - label: "bug"
    branch:
      - /fix\/.+/
  - label: "feature"
    branch:
      - /feat\/.+/
      - /feature\/.+/
  - label: "chore"
    branch:
      - /chore\/.+/
  - label: "ci/cd"
    branch:
      - /ci\/.+/
  - label: "docs"
    branch:
      - /docs\/.+/
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "ci/cd"
  - title: "📚 Documentation"
    labels:
      - "docs"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
