---
  name: Release Drafter
  on:
    push:
      branches:
        - main

  permissions:
    contents: read

  jobs:
    update-release-draft:
      permissions:
        # write permission is required to create a github release
        contents: write
        # write permission to associate commits with PRs, and automatically adds labels
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
        # Drafts your next Release notes as Pull Requests are merged into "main"
        - uses: release-drafter/release-drafter@v6
          with:
            config-name: release-drafter.yml